; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	https://github.com/npeter/ESP32AlpacaDevices2
    knolleary/PubSubClient@^2.8

[env:wemos_d1_mini32]
board = wemos_d1_mini32
monitor_port = COM10
upload_speed = 921600
build_flags = 
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEMOS_D1_MINI32
    -I src
    -I include