; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_c3_mlx90640

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
extra_scripts = pre:scripts/patch_alpaca_devices.py
lib_deps = 
	https://github.com/npeter/ESP32AlpacaDevices2
	adafruit/Adafruit MLX90640@^1.1.2
	adafruit/Adafruit MLX90614 Library@^2.1.5
	adafruit/Adafruit TSL2591 Library@^1.4.5
    knolleary/PubSubClient@^2.8

[env:esp32_c3_mlx90640]
board = esp32-c3-devkitm-1
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions/esp32_4mb_littlefs_ota.csv
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D ESP32_C3_MLX90640
	-I src
	-I include
build_src_filter =
	+<*>
	-<Dome.cpp>
	-<CoverCalibrator.cpp>
	-<Focuser.cpp>
	-<ObservingConditions.cpp>
	-<Switch.cpp>

[env:wemos_d1_mini32]
board = wemos_d1_mini32
monitor_port = COM10
upload_speed = 921600
board_build.partitions = partitions/esp32_4mb_littlefs_ota.csv
build_flags = 
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEMOS_D1_MINI32
    -I src
    -I include

[env:esp32_dome]
board = wemos_d1_mini32
upload_speed = 921600
board_build.partitions = partitions/esp32_4mb_littlefs_ota.csv
build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D ESP32_DOME
	-D WEMOS_D1_MINI32
	-I src
	-I include
build_src_filter =
	+<*>
	-<AuxSensorSwitch.cpp>
	-<CoverCalibrator.cpp>
	-<Focuser.cpp>
	-<ObservingConditions.cpp>
	-<Switch.cpp>
	-<ThermalCamera.cpp>
